---
service:
  title: restService
  gcm:
      url: https://gcm-http.googleapis.com/gcm/send
      authKey: ${GCM_KEY}
  adjuvant:
      url: http://10.132.127.212:8083
      authKey: ${ADJUVANT_KEY}

spring:
  data:
      mongodb.uri: mongodb://localhost/adjuvant
      mongodb.database: kanjuice
      mongodb.repositories.enabled: true
      rest.defaultPageSize: 200
---
server:
  contextPath: /
  port: 9090
