---
service:
  title: restService
  gcm:
      url: https://gcm-http.googleapis.com/gcm/send
      authKey: ${GCM_KEY}
  adjuvant:
      url: ${ADJUVANT_SERVER_URL}
      authKey: ${ADJUVANT_KEY}

spring:
  data:
      mongodb.uri: ${MONGODB_URL}
      mongodb.database: ${MONGODB_NAME}
      mongodb.repositories.enabled: true
      rest.defaultPageSize: 200
---
server:
  contextPath: /
  port: 9090
